CREATE TABLE endereco (
	id	INTEGER NOT NULL UNIQUE,
	logradouro	TEXT NOT NULL,
	numero	INTEGER NOT NULL,
	cep	TEXT NOT NULL,
	bairro	TEXT NOT NULL,
	cidade	TEXT NOT NULL,
	estado	TEXT NOT NULL,
	PRIMARY KEY(id AUTOINCREMENT)
)
