CREATE TABLE telefone (
	id	INTEGER NOT NULL UNIQUE,
	numero	INTEGER NOT NULL,
	ddd	INTEGER NOT NULL,
	tipo	INTEGER NOT NULL,
	PRIMARY KEY(id AUTOINCREMENT)
	FOREIGN KEY(tipo) REFERENCES telefone_tipo(id)
)
